version: "3.8"

services:
  web:
    build: .
    container_name: finance_web
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:password@db/finance
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: finance_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: finance_redis
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: finance_worker
    command: ["celery", "-A", "app.services.tasks", "worker", "--loglevel=info"]
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:password@db/finance
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  postgres_data: